### ISSUE TITLE
这个项目多节点运行成功过吗，我的项目多节点运行报错

### ISSUE THREAD

**Issue by wanglufei1** [bytedance/HLLM#30]
除了主节点其他节点报错：
[Errno 2] No such file or directory: 'xxxxx/HLLM/code/saved/HSTU/Dec-12-2024_11-36-25.log'FileNotFoundError

**Comment by ssyzeChen** [comment]
Hi~ checkpoint_dir需要所有节点均可访问

**Comment by wanglufei1** [comment]
> Hi~ checkpoint_dir需要所有节点均可访问

感谢回复，再请问个问题，我使用DeepSpeedStrategy进行训练， checkpoint_dir也需要所有节点均可访问吗？（目前单节点是运行成功的）
目前报错如下：
Traceback (most recent call last):
  File "/worker/HLLM/code/run.py", line 143, in <module>
Traceback (most recent call last):
  File "/worker/HLLM/code/run.py", line 143, in <module>
    run_loop(local_rank=local_rank, config_file=config_file, extra_args=extra_args)
  File "/worker/HLLM/code/run.py", line 117, in run_loop
    test_result = trainer.evaluate(test_loader, load_best_model=saved, show_progress=config['show_progress'])
  File "/worker/HLLM/code/REC/trainer/trainer.py", line 477, in evaluate
    run_loop(local_rank=local_rank, config_file=config_file, extra_args=extra_args)
  File "/worker/HLLM/code/run.py", line 117, in run_loop
    test_result = trainer.evaluate(test_loader, load_best_model=saved, show_progress=config['show_progress'])
  File "/worker/HLLM/code/REC/trainer/trainer.py", line 477, in evaluate
    self.lite.load(checkpoint_file, state)
  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 773, in load
    self.lite.load(checkpoint_file, state)
  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 773, in load
        remainder = self._strategy.load_checkpoint(path=path, state=unwrapped_state, strict=strict)remainder = self._strategy.load_checkpoint(path=path, state=unwrapped_state, strict=strict)

  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/lightning/fabric/strategies/deepspeed.py", line 513, in load_checkpoint
  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/lightning/fabric/strategies/deepspeed.py", line 513, in load_checkpoint
    _, client_state = engine.load_checkpoint(    
_, client_state = engine.load_checkpoint(
  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2764, in load_checkpoint
  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2764, in load_checkpoint
        load_path, client_states = self._load_checkpoint(load_dir,load_path, client_states = self._load_checkpoint(load_dir,

  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2814, in _load_checkpoint
  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2814, in _load_checkpoint
    sd_loader = SDLoaderFactory.get_sd_loader(ckpt_list, checkpoint_engine=self.checkpoint_engine)    
sd_loader = SDLoaderFactory.get_sd_loader(ckpt_list, checkpoint_engine=self.checkpoint_engine)  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 43, in get_sd_loader

  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 43, in get_sd_loader
    return MegatronSDLoader(ckpt_list, version, checkpoint_engine)    
return MegatronSDLoader(ckpt_list, version, checkpoint_engine)
  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 193, in __init__
  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 193, in __init__
    super().__init__(ckpt_list, version, checkpoint_engine)
    super().__init__(ckpt_list, version, checkpoint_engine)  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 55, in __init__

  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 55, in __init__
    self.check_ckpt_list()
    self.check_ckpt_list()  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 168, in check_ckpt_list

  File "/worker/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 168, in check_ckpt_list
    assert len(self.ckpt_list) > 0

**Comment by ssyzeChen** [comment]
checkpoint_dir 用于保存log和ckpt，不能访问无法读写

**Comment by wanglufei1** [comment]
> checkpoint_dir 用于保存log和ckpt，不能访问无法读写

好的，我之前一直以为，各个节点save 各自的信息到自己的local磁盘，load也是加载自己的local磁盘
