### ISSUE TITLE
DDP训练的ckpt文件HSTU-0.pth如何转为pytorch_model.bin

### ISSUE THREAD

**Issue by wanglufei1** [bytedance/HLLM#34]
咨询一下哈，DDP训练的ckpt文件HSTU-0.pth如何转为pytorch_model.bin，我尝试rename后加载信息如下，显示缺失了keys

25 Dec 20:41    INFO  Eval only model load from /home/ma-user/modelarts/nfs_dir/lum/saved/HSTU-large-Books-neg28k/pytorch_model.bin
25 Dec 20:41    INFO  msg.unexpected_keys = ['model', 'optimizer', 'config', 'epoch', 'cur_step', 'best_valid_score', 'rng_state', 'npu_rng_state']
25 Dec 20:41    INFO  msg.missing_keys = ['logit_scale', '_attn_mask', 'position_embedding.weight', '_hstu._attention_layers.0._uvqk', '_hstu._attention_layers.0._rel_attn_bias._ts_w', '_hstu._attention_layers.0._rel_attn_bias._pos_w', '_hstu._attention_layers.0._o.weight', '_hstu._attention_layers.0._o.bias', '_hstu._attention_layers.1._uvqk', '_hstu._attention_layers.1._rel_attn_bias._ts_w', '_hstu._attention_layers.1._rel_attn_bias._pos_w', '_hstu._attention_layers.1._o.weight', '_hstu._attention_layers.1._o.bias', '_hstu._attention_layers.2._uvqk', '_hstu._attention_layers.2._rel_attn_bias._ts_w', '_hstu._attention_layers.2._rel_attn_bias._pos_w', '_hstu._attention_layers.2._o.weight', '_hstu._attention_layers.2._o.bias', '_hstu._attention_layers.3._uvqk', '_hstu._attention_layers.3._rel_attn_bias._ts_w', '_hstu._attention_layers.3._rel_attn_bias._pos_w', '_hstu._attention_layers.3._o.weight', '_hstu._attention_layers.3._o.bias', '_hstu._attention_layers.4._uvqk', '_hstu._attention_layers.4._rel_attn_bias._ts_w', '_hstu._attention_layers.4._rel_attn_bias._pos_w', '_hstu._attention_layers.4._o.weight', '_hstu._attention_layers.4._o.bias', '_hstu._attention_layers.5._uvqk', '_hstu._attention_layers.5._rel_attn_bias._ts_w', '_hstu._attention_layers.5._rel_attn_bias._pos_w', '_hstu._attention_layers.5._o.weight', '_hstu._attention_layers.5._o.bias', '_hstu._attention_layers.6._uvqk', '_hstu._attention_layers.6._rel_attn_bias._ts_w', '_hstu._attention_layers.6._rel_attn_bias._pos_w', '_hstu._attention_layers.6._o.weight', '_hstu._attention_layers.6._o.bias', '_hstu._attention_layers.7._uvqk', '_hstu._attention_layers.7._rel_attn_bias._ts_w', '_hstu._attention_layers.7._rel_attn_bias._pos_w', '_hstu._attention_layers.7._o.weight', '_hstu._attention_layers.7._o.bias', '_hstu._attention_layers.8._uvqk', '_hstu._attention_layers.8._rel_attn_bias._ts_w', '_hstu._attention_layers.8._rel_attn_bias._pos_w', '_hstu._attention_layers.8._o.weight', '_hstu._attention_layers.8._o.bias', '_hstu._attention_layers.9._uvqk', '_hstu._attention_layers.9._rel_attn_bias._ts_w', '_hstu._attention_layers.9._rel_attn_bias._pos_w', '_hstu._attention_layers.9._o.weight', '_hstu._attention_layers.9._o.bias', '_hstu._attention_layers.10._uvqk', '_hstu._attention_layers.10._rel_attn_bias._ts_w', '_hstu._attention_layers.10._rel_attn_bias._pos_w', '_hstu._attention_layers.10._o.weight', '_hstu._attention_layers.10._o.bias', '_hstu._attention_layers.11._uvqk', '_hstu._attention_layers.11._rel_attn_bias._ts_w', '_hstu._attention_layers.11._rel_attn_bias._pos_w', '_hstu._attention_layers.11._o.weight', '_hstu._attention_layers.11._o.bias', '_hstu._attention_layers.12._uvqk', '_hstu._attention_layers.12._rel_attn_bias._ts_w', '_hstu._attention_layers.12._rel_attn_bias._pos_w', '_hstu._attention_layers.12._o.weight', '_hstu._attention_layers.12._o.bias', '_hstu._attention_layers.13._uvqk', '_hstu._attention_layers.13._rel_attn_bias._ts_w', '_hstu._attention_layers.13._rel_attn_bias._pos_w', '_hstu._attention_layers.13._o.weight', '_hstu._attention_layers.13._o.bias', '_hstu._attention_layers.14._uvqk', '_hstu._attention_layers.14._rel_attn_bias._ts_w', '_hstu._attention_layers.14._rel_attn_bias._pos_w', '_hstu._attention_layers.14._o.weight', '_hstu._attention_layers.14._o.bias', '_hstu._attention_layers.15._uvqk', '_hstu._attention_layers.15._rel_attn_bias._ts_w', '_hstu._attention_layers.15._rel_attn_bias._pos_w', '_hstu._attention_layers.15._o.weight', '_hstu._attention_layers.15._o.bias', 'item_embedding.weight']
25 Dec 20:41    INFO  Use DDP strategy

**Comment by wanglufei1** [comment]
补充：我取ckpt['model']可以正常工作了
ckpt = torch.load(ckpt_path, map_location='cpu') =》ckpt = torch.load(ckpt_path, map_location='cpu')['model']

但我在amazon_books上训练的HSTU模型，去推理**采样的amazon_books_10K_user数据**时加载模型报错，这个有办法规避吗
Traceback (most recent call last):
  File "/home/ma-user/modelarts/user-job-dir/HLLM/code/run.py", line 143, in <module>
    run_loop(local_rank=local_rank, config_file=config_file, extra_args=extra_args)
  File "/home/ma-user/modelarts/user-job-dir/HLLM/code/run.py", line 104, in run_loop
    msg = trainer.model.load_state_dict(ckpt, False)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for HSTU:
	size mismatch for item_embedding.weight: copying a param with shape torch.Size([686624, 64]) from checkpoint, the shape in current model is torch.Size([90907, 64]).

**Comment by wanglufei1** [comment]
改了三行代码跑通了，结果与预期一致
run.py
![image](https://github.com/user-attachments/assets/eb52c19d-df96-442b-ba7a-fae7381b4889)
hstu.py
![image](https://github.com/user-attachments/assets/8fa5d37d-c296-494e-bca3-4b88814081eb)
trainer.py
![image](https://github.com/user-attachments/assets/8abceb7f-2ecd-4b97-b8a6-cb13fe39d854)
