### ISSUE TITLE
About the problem of the parameter --text_keys

### ISSUE THREAD

**Issue by Maribel-Hearn** [bytedance/HLLM#4]
I try to run this code ,but the parameter --text_keys seems to lead a lot of error.First,I use the `Pixel200K` dataset,here is my parameter setting:
```
python3 main.py \
--config_file overall/LLM_deepspeed.yaml HLLM/HLLM.yaml \
--loss nce  \
--epochs 5 \
--dataset Pixel200K  \
--train_batch_size 16 \
--MAX_TEXT_LENGTH 256 \
--MAX_ITEM_LIST_LENGTH 10 \
--checkpoint_dir /root/HLLM/ckpt \
--optim_args.learning_rate 1e-4 \
--item_pretrain_dir ../base-model/tinyllm \
--user_pretrain_dir ../base-model/tinyllm \
--text_path /root/HLLM/information \
--text_keys '[\"title\", \"tag\", \"description\"]'
```
but it is happend:
```
nce
Unable to convert the string 'nce' to None / Bool / Float / Int, retaining the original string.
5
Pixel200K
Unable to convert the string 'Pixel200K' to None / Bool / Float / Int, retaining the original string.
16
256
10
/root/HLLM/ckpt
Unable to convert the string '/root/HLLM/ckpt' to None / Bool / Float / Int, retaining the original string.
1e-4
../base-model/tinyllm
Unable to convert the string '../base-model/tinyllm' to None / Bool / Float / Int, retaining the original string.
../base-model/tinyllm
Unable to convert the string '../base-model/tinyllm' to None / Bool / Float / Int, retaining the original string.
/root/HLLM/information
Unable to convert the string '/root/HLLM/information' to None / Bool / Float / Int, retaining the original string.
["title",
    value = json.loads(value)
json.decoder.JSONDecodeError: Expecting value: line 1 column 10 (char 9)
```
So i change the dataset to `amazon book`, the parament I change the text_key to `--text_keys '[\"title\",\"description\"]'`,but it still have some problem:
```
  File "/root/HLLM/code/run.py", line 140, in <module>
    run_loop(local_rank=local_rank, config_file=config_file, extra_args=extra_args)
  File "/root/HLLM/code/run.py", line 86, in run_loop
    train_loader, valid_loader, test_loader = bulid_dataloader(config, dataload)
  File "/root/HLLM/code/REC/data/utils.py", line 60, in bulid_dataloader
    train_data = train_set_class(config, dataload)
  File "/root/HLLM/code/REC/data/dataset/trainset.py", line 123, in __init__
    self.load_content()
  File "/root/HLLM/code/REC/data/dataset/trainset.py", line 130, in load_content
    self.env = self.env[self.text_keys + ['item_id']]
  File "/root/miniconda3/lib/python3.10/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/root/miniconda3/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/root/miniconda3/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['title', 'description'] not in index"
```
Strangely，I set the text_keys to `--text_keys '[]'` ,it seems can work,but when run to ready to train ,it still have the error:
```
 File "/root/HLLM/code/run.py", line 111, in run_loop
    best_valid_score, best_valid_result = trainer.fit(
  File "/root/HLLM/code/REC/trainer/trainer.py", line 342, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "/root/HLLM/code/REC/trainer/trainer.py", line 191, in _train_epoch
    losses = self.model(data)
RuntimeError: `dual_gemm_silu_identity_mul` does not support this input: Error Misaligned Operand
Train [  0/  5]:   0%|                                | 0/63286 [00:02<?, ?it/s]
```
In  `Pixel200K`,I try the same parameter  `--text_keys '[]'`,it also meet the same error.So I feel confused, how can I fix this problem?
About my environment:
```
Python==3.10
CUDA==12.1
torch==2.1.0
transformers== 4.44.2
deepspeed ==0.15.1
flash-attn==2.5.9.post1
xformers==0.0.23.post1
accelerate==0.34.2
```

**Comment by ssyzeChen** [comment]
It seems really strange, we haven't met this problem before, could you please set text_keys directly in "overall/LLM_deepspeed.yaml" and do not pass through cli.

**Comment by Maribel-Hearn** [comment]
> It seems really strange, we haven't met this problem before, could you please set text_keys directly in "overall/LLM_deepspeed.yaml" and do not pass through cli.

Thanks you answer! I remove the text keys:
```
python3 main.py \
--config_file overall/LLM_deepspeed.yaml HLLM/HLLM.yaml \
--loss nce  \
--epochs 5 \
--dataset Pixel200K  \
--train_batch_size 16 \
--MAX_TEXT_LENGTH 256 \
--MAX_ITEM_LIST_LENGTH 10 \
--checkpoint_dir /root/HLLM/ckpt \
--optim_args.learning_rate 1e-4 \
--item_pretrain_dir ../base-model/tinyllm \
--user_pretrain_dir ../base-model/tinyllm \
--text_path /root/HLLM/information
```
 and in  LLM_deepspeed.yaml,I keep the parameter in default : 
```text_keys: ['title', 'tag', 'description']```

However, in Pixel200K, it still meet the same problem:
```
/root/HLLM/code/REC/data/dataset/collate_fn.py:43: UserWarning: An output with one or more elements was resized since it had shape [1056], which does not match the required output shape [16, 11, 6]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  return torch.stack(batch, 0, out=out)
Traceback (most recent call last):
  File "/root/HLLM/code/run.py", line 140, in <module>
    run_loop(local_rank=local_rank, config_file=config_file, extra_args=extra_args)
  File "/root/HLLM/code/run.py", line 111, in run_loop
    best_valid_score, best_valid_result = trainer.fit(
  File "/root/HLLM/code/REC/trainer/trainer.py", line 342, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "/root/HLLM/code/REC/trainer/trainer.py", line 191, in _train_epoch
    losses = self.model(data)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 141, in forward
    output = self._forward_module(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1899, in forward
    loss = self.module(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/HLLM/code/REC/model/HLLM/hllm.py", line 194, in forward
    neg_embedding = self.forward_item_emb(neg_input_ids, neg_position_ids, neg_cu_input_lens, self.item_emb_token_n, self.item_emb_tokens, self.item_llm)
  File "/root/HLLM/code/REC/model/HLLM/hllm.py", line 160, in forward_item_emb
    model_out = llm(inputs_embeds=inputs_embeds.unsqueeze(0), cu_input_lens=cu_input_lens, position_ids=position_ids.unsqueeze(0))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/HLLM/code/REC/model/HLLM/modeling_llama.py", line 1259, in forward
    outputs = self.model(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/HLLM/code/REC/model/HLLM/modeling_llama.py", line 1131, in forward
    layer_outputs = decoder_layer(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/HLLM/code/REC/model/HLLM/modeling_llama.py", line 826, in forward
    hidden_states = self.mlp(hidden_states)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/HLLM/code/REC/model/HLLM/modeling_llama.py", line 516, in forward
    down_proj = xformers_swiglu(
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/ops/swiglu_op.py", line 387, in swiglu
    return op(x, w1w2, b1b2, w3, b3).reshape([*batch_shape, -1])
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/ops/swiglu_op.py", line 201, in __call__
    return self.op(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: `dual_gemm_silu_identity_mul` does not support this input: Error Misaligned Operand
Train [  0/  5]:   0%|                                | 0/18971 [00:01<?, ?it/s]
```
And in Amazon book,, in LLM_deepspeed.yaml, I set the text_keys to ` text_keys: ['title', 'description']`,it still have some problem:
```
INFO  Item prompt: Compress the following sentence into embedding:
Traceback (most recent call last):
  File "/root/HLLM/code/run.py", line 140, in <module>
    run_loop(local_rank=local_rank, config_file=config_file, extra_args=extra_args)
  File "/root/HLLM/code/run.py", line 86, in run_loop
    train_loader, valid_loader, test_loader = bulid_dataloader(config, dataload)
  File "/root/HLLM/code/REC/data/utils.py", line 60, in bulid_dataloader
    train_data = train_set_class(config, dataload)
  File "/root/HLLM/code/REC/data/dataset/trainset.py", line 123, in __init__
    self.load_content()
  File "/root/HLLM/code/REC/data/dataset/trainset.py", line 130, in load_content
    self.env = self.env[self.text_keys + ['item_id']]
  File "/root/miniconda3/lib/python3.10/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/root/miniconda3/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/root/miniconda3/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['title', 'description'] not in index"
```
So I still feel confuse, how can I solve this problem?

**Comment by ssyzeChen** [comment]
1. Could you please remove xformers ops in your env first ? we'll update `modeling_llama.py` later becase we do not use xformers in training. We are sorry for some unexpected problems with this pkg.
2. Could you please check your item_information file for books, there should be only item_id | description | title in the csv file. We fixed the incorrect link several days ago in readme.
Hope these msg can help you.

**Comment by ssyzeChen** [comment]
We have fixed the issue caused by incorrect import. Please check for the update.

**Comment by Maribel-Hearn** [comment]
> We have fixed the issue caused by incorrect import. Please check for the update.

Thanks so much for your work! I have updated the Amazon Book dataset and the code, and tried running it again. This time, everything worked without any error. The model I guess I need prepare more GPUs, so I might need to find another time to run it completely. But regardless, I really appreciate your contributions!
