### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by threestone965** [bytedance/HLLM#8]
精彩的工作，感谢作者的分享。

### 1. A100(80g)*16 + HLLM/reproduce/HLLM-Books-neg512.sh进行训练，并对脚本做了部分修改（epoch=1, **num_negatives=32**），worker节点爆显存错误，具体错误如下：

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.46 GiB. GPU 0 has a total capacty of 79.17 GiB of which 11.75 GiB is free. Including non-PyTorch memory, this process has 67.41 GiB memory in use. Of the allocated memory 59.52 GiB is allocated by PyTorch, and 6.98 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### 2. A100(80g)*16 + HLLM/reproduce/HLLM-Books-neg512.sh进行训练，并对脚本做了部分修改（epoch=1, **num_negatives=1**），worker节点爆Lightning相关错误，具体错误如下：

 Traceback (most recent call last):
   File "/home/work/code/HLLM/code/run.py", line 139, in <module>
     run_loop(local_rank=local_rank, config_file=config_file, extra_args=extra_args)
   File "/home/work/code/HLLM/code/run.py", line 110, in run_loop
     best_valid_score, best_valid_result = trainer.fit(
   File "/home/work/code/HLLM/code/REC/trainer/trainer.py", line 329, in fit
     self.lite.launch()
   File "/home/work/miniconda3/envs/img/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 843, in launch
     return self._wrap_and_launch(function, self, *args, **kwargs)
   File "/home/work/miniconda3/envs/img/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 928, in _wrap_and_launch
     return launcher.launch(to_run, *args, **kwargs)
   File "/home/work/miniconda3/envs/img/lib/python3.10/site-packages/lightning/fabric/strategies/launchers/subprocess_script.py", line 101, in launch
     self.cluster_environment.validate_settings(num_devices=self.num_processes, num_nodes=self.num_nodes)
   File "/home/work/miniconda3/envs/img/lib/python3.10/site-packages/lightning/fabric/plugins/environments/torchelastic.py", line 90, in validate_settings
     raise ValueError(
 ValueError: You set `devices=8` and `num_nodes=16` in Lightning, but the product (8 * 16) does not match the world size (16).

**Comment by cijiezheng** [comment]
self.lite = L.Fabric(accelerator='gpu', devices=world_size, strategy=strategy, precision=precision, num_nodes=nnodes)

set param devices=world_size to match your num_nodes
