### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by JunZhangJz** [bytedance/HLLM#9]
运行sh HLLM-Books-neg512.sh脚本时 报错
Traceback (most recent call last):
  File "/home/zhangjun/miniconda3/envs/hllm/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0', 'console_scripts', 'torchrun')())
  File "/home/zhangjun/miniconda3/envs/hllm/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/zhangjun/miniconda3/envs/hllm/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/zhangjun/miniconda3/envs/hllm/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/zhangjun/miniconda3/envs/hllm/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zhangjun/miniconda3/envs/hllm/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError
这个问题可能是什么原因导致的？是否有建议的解决办法？感谢作者！

**Comment by ssyzeChen** [comment]
Hi~ Could you please give more logs about this? It's difficult to debug with these logs. You could check your environment variables and run with a single GPU first.
